name: CI

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - target_triple: arm-linux-musleabi
            target_arch: armel
            target_os: Linux
          - target_triple: arm-linux-musleabihf
            target_arch: armhf
            target_os: Linux
          - target_triple: armeb-linux-musleabi
            target_arch: armel
            target_os: Linux
          - target_triple: armeb-linux-musleabihf
            target_arch: armhf
            target_os: Linux
          - target_triple: thumb-linux-musleabi
            target_arch: thumbel
            target_os: Linux
          - target_triple: thumb-linux-musleabihf
            target_arch: thumbhf
            target_os: Linux
          - target_triple: thumbeb-linux-musleabi
            target_arch: thumbel
            target_os: Linux
          - target_triple: thumbeb-linux-musleabihf
            target_arch: thumbhf
            target_os: Linux
          - target_triple: thumb-windows-gnu
            target_arch: thumb
            target_os: Windows
          - target_triple: aarch64-linux-musl
            target_arch: aarch64
            target_os: Linux
          - target_triple: aarch64-windows-gnu
            target_arch: aarch64
            target_os: Windows
          - target_triple: aarch64_be-linux-musl
            target_arch: aarch64_be
            target_os: Linux
          - target_triple: loongarch64-linux-musl
            target_arch: loongarch64
            target_os: Linux
          - target_triple: mips-linux-musleabi
            target_arch: mips
            target_os: Linux
          - target_triple: mips-linux-musleabihf
            target_arch: mips
            target_os: Linux
          - target_triple: mipsel-linux-musleabi
            target_arch: mipsel
            target_os: Linux
          - target_triple: mipsel-linux-musleabihf
            target_arch: mipsel
            target_os: Linux
          - target_triple: mips64-linux-muslabin32
            target_arch: mips64
            target_os: Linux
          - target_triple: mips64el-linux-muslabin32
            target_arch: mips64el
            target_os: Linux
          - target_triple: powerpc-linux-musleabi
            target_arch: powerpc
            target_os: Linux
          - target_triple: powerpc-linux-musleabihf
            target_arch: powerpc
            target_os: Linux
          - target_triple: powerpc64-linux-musl
            target_arch: powerpc64
            target_os: Linux
          - target_triple: powerpc64le-linux-musl
            target_arch: powerpc64le
            target_os: Linux
          - target_triple: riscv32-linux-musl
            target_arch: riscv32
            target_os: Linux
          - target_triple: riscv64-linux-musl
            target_arch: riscv64
            target_os: Linux
          - target_triple: s390x-linux-musl
            target_arch: s390x
            target_os: Linux
          - target_triple: x86-linux-musl
            target_arch: x86
            target_os: Linux
          - target_triple: x86-windows-gnu
            target_arch: x86
            target_os: Windows
          - target_triple: x86_64-linux-musl
            target_arch: x86_64
            target_os: Linux
          - target_triple: x86_64-linux-muslx32
            target_arch: x86_64
            target_os: Linux
          - target_triple: x86_64-windows-gnu
            target_arch: x86_64
            target_os: Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MinGW Binutils
        run: |
          if [[ "${{ matrix.target_triple }}" == "x86_64-windows-gnu" ]]; then
            curl -LkSs https://github.com/mstorsjo/llvm-mingw/releases/download/20250114/llvm-mingw-20250114-msvcrt-ubuntu-20.04-x86_64.tar.xz | xz -d | tar -x
            sudo ln -sf $(pwd)/llvm-mingw-20250114-msvcrt-ubuntu-20.04-x86_64/bin/x86_64-w64-mingw32-windres /usr/bin/windres
          elif [[ "${{ matrix.target_triple }}" == "aarch64-windows-gnu" ]]; then
            curl -LkSs https://github.com/mstorsjo/llvm-mingw/releases/download/20250114/llvm-mingw-20250114-msvcrt-ubuntu-20.04-x86_64.tar.xz | xz -d | tar -x
            sudo ln -sf $(pwd)/llvm-mingw-20250114-msvcrt-ubuntu-20.04-x86_64/bin/aarch64-w64-mingw32-windres /usr/bin/windres
          elif [[ "${{ matrix.target_triple }}" == "x86-windows-gnu" ]]; then
            curl -LkSs https://github.com/mstorsjo/llvm-mingw/releases/download/20250114/llvm-mingw-20250114-msvcrt-ubuntu-20.04-x86_64.tar.xz | xz -d | tar -x
            sudo ln -sf $(pwd)/llvm-mingw-20250114-msvcrt-ubuntu-20.04-x86_64/bin/i686-w64-mingw32-windres /usr/bin/windres
          elif [[ "${{ matrix.target_triple }}" == "thumb-windows-gnu" ]]; then
            curl -LkSs https://github.com/mstorsjo/llvm-mingw/releases/download/20250114/llvm-mingw-20250114-msvcrt-ubuntu-20.04-x86_64.tar.xz | xz -d | tar -x
            sudo ln -sf $(pwd)/llvm-mingw-20250114-msvcrt-ubuntu-20.04-x86_64/bin/armv7-w64-mingw32-windres /usr/bin/windres
          fi

      - name: Build
        run: ./build.sh 4.0.2 1.12.1 ${{ matrix.target_triple }} ${{ matrix.target_arch }} ${{ matrix.target_os }}

      - name: Compress
        run: |
          tarball_name=cmake-${{ matrix.target_triple }}
          echo tarball_name=${tarball_name} >> ${GITHUB_ENV}
          mv install/4.0.2-${{ matrix.target_triple }} ${tarball_name}
          tar -cf - ${tarball_name} | xz -T0 -9e --lzma2=dict=256MiB > ${tarball_name}.tar.xz

      - name: Upload release
        uses: ncipollo/release-action@v1.16.0
        with:
          tag: "4.0.2"
          artifacts: ${{env.tarball_name}}.tar.xz
          allowUpdates: true
          replacesArtifacts: true
          body: ''
